apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notification-deployment.yml
- notification-service.yml
- notification-mongodb.yml
- notification-destination-rule.yml
- notification-virtual-service.yml
  
images:
- name: l00162972/diss22-notification
  newName: l00162972/diss22-notification
  newTag: a86e12de
