apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- product-deployment.yml
- product-service.yml
- product-postgresql.yml
- product-destination-rule.yml
- product-virtual-service.yml
  
images:
- name: l00162972/diss22-product
  newName: l00162972/diss22-product
  newTag: 10d00e1d
