apiVersion: v1
kind: Secret
metadata:
  name: product-postgresql
  namespace: jhipster
  labels:
    app: product-postgresql
type: Opaque
data:
  postgresql-password: MWZiNzM2ODdiZWU3NDM2YzRhNmRhNzllMjIxZDNiNjhkN2FlZmFmNTE5NTViZDU4YjNkMDgwNGY3ZmY2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgresql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-postgresql
  template:
    metadata:
      labels:
        app: product-postgresql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres@sha256:d6809f4833ca6caf11a4969a7f41420d3e5fcf26b8c9ca4253c34d5a5fa377cc
          env:
            - name: POSTGRES_USER
              value: product
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product-postgresql
  namespace: jhipster
spec:
  selector:
    app: product-postgresql
  ports:
    - port: 5432
