apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jhipster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JoseSunoj/Diss22-IaC.git
    targetRevision: main
    path: manifests/application/overlays/jhipster
  destination:
    server: https://kubernetes.default.svc
    namespace: jhipster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
